name: FitNesse CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package
    
    - name: Create directories
      run: |
        mkdir -p target/classes
        mkdir -p fitnesse
        mkdir -p target/fitnesse-results
    
    - name: Download FitNesse
      run: |
        wget -O fitnesse/fitnesse-standalone.jar https://github.com/ngocnghia81/Fitnesse/raw/main/fitnesse-standalone.jar
    
    - name: Set up classpath properties
      run: |
        echo "CLASSPATH=fitnesse/fitnesse-standalone.jar:target/classes:target/dependencies/*" > plugins.properties
        echo "Test.CLASSPATH=fitnesse/fitnesse-standalone.jar:target/classes:target/dependencies/*" >> plugins.properties
    
    - name: Compile fixtures
      run: |
        javac -cp "fitnesse/fitnesse-standalone.jar:target/classes" -d target/classes $(find src/main/java -name "*.java")
    
    - name: Run FitNesse Tests
      run: |
        java -jar fitnesse/fitnesse-standalone.jar -c "CalculatorTests?suite&format=junit" -d . -r src/test/fitnesse -p 9125 -o -f plugins.properties -b target/fitnesse-results/result.xml
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: fitnesse-test-results
        path: target/fitnesse-results
        
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: 'target/fitnesse-results/result.xml'
        fail_on_failure: false 